---
on:
  push:
    branches:
      - integration
jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export game to Github
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: export game
        id: export
        uses: firebelley/godot-export@v5.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          env:
            GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
            ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GH_CREDENTIALS }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
  release_testing_html:
    runs-on: ubuntu-latest
    needs: export_game
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: latest
          file: ticker-html.zip
          token: ${{ secrets.GH_CREDENTIALS }}
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: ticker-tb
          ITCH_USER: chewiecb
          PACKAGE: ticker-html.zip
          VERSION: ${{ steps.download-html.outputs.version }}
