on:
  release:
    types: [published]

jobs:
  testing_release_html:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/integration'
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: ticker.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: ticker-tb
          ITCH_USER: chewiecb
          PACKAGE: ticker-html.zip
          VERSION: ${{ steps.download-html.outputs.version }}
  release_html:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: corge-html.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: ticker
          ITCH_USER: chewiecb
          PACKAGE: ticker-html.zip
          VERSION: ${{ steps.download-html.outputs.version }}
