on:
  pull_request:
    branches: 
      - integration
    types: [closed]

jobs:
  release_testing_html:
    runs-on: ubuntu-latest
    steps:
      - name: download HTML5
        id: download-html
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "latest"
          file: ticker-html.zip
          token: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: ticker-tb
          ITCH_USER: chewiecb
          PACKAGE: ticker-html.zip
          VERSION: ${{ steps.download-html.outputs.version }}